# Generated by Django 4.2.2 on 2023-06-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dzolali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=255)),
                ('Brand_Name', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Remark', models.TextField()),
            ],
        ),
    ]
