# Generated by Django 4.2.2 on 2023-06-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITEMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDS', models.CharField(max_length=100)),
                ('Item_Name', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Condition', models.TextField()),
            ],
        ),
    ]
