# Generated by Django 4.2.2 on 2023-06-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AlterField(
            model_name='items',
            name='IDS',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
