# Generated by Django 4.2.2 on 2023-07-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_leased'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Remark', models.TextField()),
            ],
        ),
    ]
