# Generated by Django 4.2.2 on 2023-06-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_items_id_alter_items_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='IDS',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
