# Generated by Django 4.2.2 on 2023-06-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_kana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITEMS',
        ),
    ]
