# Generated by Django 4.2.2 on 2023-08-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_books'),
        ('alumni', '0007_delete_items'),
    ]

    operations = [
    ]
