# Generated by Django 4.2.2 on 2023-08-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_merge_0004_books_0007_delete_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kana',
        ),
    ]
